### PR TITLE
Two small updates to be compatible with newer RN

### PR DESCRIPTION
**Pull request by bitfabrikken**
Not sure when

### CODE REVIEW

**Comment by AndreYonadam** [comment]
First off all thank you for this contribution! I have a question, does the [readme](https://github.com/AndreYonadam/react-native-scrolling-images#readme) need to be updated for this change?

**Comment by bitfabrikken** [comment]
Maybe a description for useNativeDriver?

**Comment by AndreYonadam** [comment]
@bitfabrikken Sorry it's actually been a while since I used React Native haha. With your changes does the implementation example on the readme change:
```tsx
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

import ScrollingBackground from 'react-native-scrolling-images';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <ScrollingBackground
          style={styles.scrollingBackground}
          speed={20}
          direction={"left"}
          images={[require("./assets/greenOrange.png"),require("./assets/blueOrange.png")]}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%"
  },
  scrollingBackground: {
    backgroundColor: "#0B7483"
  },
});
```

Thank you for your changes. I just wanted to make sure readme example still works for any changes you introduced.

**Comment by bitfabrikken** [comment]
Well it's an optional prop that defaults to false, so could be:

```js
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

import ScrollingBackground from 'react-native-scrolling-images';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <ScrollingBackground
          style={styles.scrollingBackground}
          speed={20}
          direction={"left"}
          images={[require("./assets/greenOrange.png"),require("./assets/blueOrange.png")]}
          useNativeDriver={true}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%"
  },
  scrollingBackground: {
    backgroundColor: "#0B7483"
  },
});
```

**Comment by AndreYonadam** [comment]
Thanks! If `useNativeDriver=false` offers better performance then I think we can just keep it as is.

**Pull request merged**
